### ISSUE TITLE
bad results on unseen data

### ISSUE THREAD

**Issue by PGogo** [e4s2022/e4s#4]
Thanks for your work! 
I wonder have you ever tried testing on the images that are not sampled from FFHQ? I test it on my daily images, and it returns bad results. (aligned faces are used and try on different resolution)

**Comment by e4s2022** [comment]
Would you mind showing the input and output?

**Comment by PGogo** [comment]
> Would you mind showing the input and output?

source:
![input3](https://user-images.githubusercontent.com/41355904/236446611-576a62a2-0172-4e89-8970-f85e20d3e4e2.jpg)
target:
![input0](https://user-images.githubusercontent.com/41355904/236446665-fc4fb8da-3560-43f5-a28b-1737b8ff5422.jpg)
![input1](https://user-images.githubusercontent.com/41355904/236446672-eb7d7ab7-765b-4cdb-87b0-8efeb106a7eb.jpg)
![input2](https://user-images.githubusercontent.com/41355904/236446677-44c158b8-edfa-4092-8515-76ff03fb469c.jpg)
![input3](https://user-images.githubusercontent.com/41355904/236446681-62f8734e-13fb-45dd-8c3f-6136cd055a8f.jpg)
swapped:
![output0](https://user-images.githubusercontent.com/41355904/236446739-112363ab-41cf-439d-8d02-a399f628f18a.jpg)
![output1](https://user-images.githubusercontent.com/41355904/236446750-e26baf7f-58e7-4da8-a351-fef7265cc13e.jpg)
![output2](https://user-images.githubusercontent.com/41355904/236446761-9b8e06a3-6614-4463-a0f2-9d5bfb007f2c.jpg)
![output3](https://user-images.githubusercontent.com/41355904/236446767-bed35076-d07b-4490-8a41-1456c7dddce5.jpg)

The last one is for reconstruction and it fails too.

**Comment by e4s2022** [comment]
Are these original images available? Did you align the faces with the procedure [here](https://github.com/e4s2022/e4s/blob/bc864d3757beb9d1f1027faf26c91d0f5871c2a1/scripts/face_swap.py#L175)?

**Comment by PGogo** [comment]
> Are these original images available? Did you align the faces with the procedure [here](https://github.com/e4s2022/e4s/blob/bc864d3757beb9d1f1027faf26c91d0f5871c2a1/scripts/face_swap.py#L175)?

Here are the original images:
![34edc47e3eee4f6c95404a18263b5501](https://user-images.githubusercontent.com/41355904/236803324-dde0c0f1-7853-4a80-b7a3-ce223b4e889f.jpeg)
![innocences_5_c4c8696bbf62f2ab250959fa761623adori](https://user-images.githubusercontent.com/41355904/236803332-9c60734e-82dd-40b6-bdd3-b977d001f1c2.jpg)
I did not align with the procedure before.
But when I make it by simply setting "need_crop=True" and input the original images. The results are also somehow ...emm.. weird as below? Especially around the edges of the face. Could you test on these images or any other daily images in case of mistakes by myself?
![34edc47e3eee4f6c95404a18263b5501](https://user-images.githubusercontent.com/41355904/236803384-7a2e7005-3f04-42a6-ab6c-a99092d77542.jpeg)

**Comment by e4s2022** [comment]
We apply Laplacian blending around the face boundary, please check #5 for reference. 

Will investigate your case a bit later.

**Comment by ds-nat-j** [comment]
This is still somewhat alright, when I'm testing for these sample images I'm getting really terrible results.
However with the example input images the results are fine which is weird.

![swap_source_to_target (1)](https://github.com/e4s2022/e4s/assets/98014515/7ff67777-a2f9-4252-8b69-029f49a0a546)

**Comment by e4s2022** [comment]
Hi, guys,

I tried the case as @PGogo provided, and would like to point some concepts that you would need when handling your test data:

1. Face cropping. Please keep in mind that our e4s model was trained on aligned face, hence, I don't think directly use photos like profile would produce desired result. The basic logic here is, cropping the face from source and target pictures first(if needed), then the swapping procedure, finally pasting the swapped face to orginal target picture. Please consider the cropping arg https://github.com/e4s2022/e4s/blob/f55084d632b3a9026868126792f82507dd48eb8b/scripts/face_swap.py#L180-L192  to match your case accordingly.

2. Laplacian blending. When pasting the swapped face to original target picture, hard pasting would make the area around the face boundary a little bit unnatural. Hence, I recommend to use the `--lap_bld` option that used in `scripts/face_swap.py`. https://github.com/e4s2022/e4s/blob/f55084d632b3a9026868126792f82507dd48eb8b/src/options/swap_options.py#L14

3. The order of mask composition.  As discussed in #1, You can try to set `hair_first = False` [here](https://github.com/e4s2022/e4s/blob/bc864d3757beb9d1f1027faf26c91d0f5871c2a1/src/utils/swap_face_mask.py#L47).


After few tuning (cropping + Laplacian blending + `hair_first = False`), here is my result:
 
![swap_source_to_target](https://github.com/e4s2022/e4s/assets/107909552/176ae481-f170-4dcd-96ca-ab0abd84d3d7)


Currently, we focus on face swapping with aligned face as similar to the most works in the literature. Feel free to play with these parameters. 


Sorry for the slow reply, I am busy with other stuffs recently. Hope this helps. : )

**Comment by LeoLovechest** [comment]
when you say alighned faces are you refering to the source and target being alighned or talking about facing the camera with a straight/ upright head?

**Comment by PGogo** [comment]
> Hi, guys, @PGogo, @ds-nat-j
> 
> I tried with the case as @PGogo provided, and would like to point out some concepts that you would need when handling your test data:
> 
> 1. Face cropping. Please keep in mind that our e4s model was trained on aligned faces, hence, I don't think directly use photos like profile would produce desired result. The basic logic here is, cropping the face from source and target pictures first(if needed), then the swapping procedure, finally pasting the swapped face to the original target picture. Please consider the cropping arg https://github.com/e4s2022/e4s/blob/f55084d632b3a9026868126792f82507dd48eb8b/scripts/face_swap.py#L180-L192
>      to match your case accordingly.
> 2. Laplacian blending. When pasting the swapped face to original target picture, hard pasting would make the area around the face boundary a little bit unnatural. Hence, I recommend to use the `--lap_bld` option that used in `scripts/face_swap.py`. https://github.com/e4s2022/e4s/blob/f55084d632b3a9026868126792f82507dd48eb8b/src/options/swap_options.py#L14
> 3. The order of mask composition.  As discussed in [The inference result is not good #1](https://github.com/e4s2022/e4s/issues/1), You can try to set `hair_first = False` [here](https://github.com/e4s2022/e4s/blob/bc864d3757beb9d1f1027faf26c91d0f5871c2a1/src/utils/swap_face_mask.py#L47).
> 
> After few tuning (cropping + Laplacian blending + `hair_first = False`), here is my result:
> 
> ![swap_source_to_target](https://user-images.githubusercontent.com/107909552/241113716-176ae481-f170-4dcd-96ca-ab0abd84d3d7.png)
> 
> Currently, we focus on face swapping with aligned face as similar to the most works in the literature. Feel free to play with these parameters.
> 
> Sorry for the slow reply, I am busy with other stuffs recently. Hope this helps. : )

Thank you for your detailed response！
