### ISSUE TITLE
help :)

### ISSUE THREAD

**Issue by ketakachono** [e4s2022/e4s#8]
I had to move the src folder inside scripts to fix paths

(e4s) C:\Users\user\e4s>python scripts/face_swap.py --source=example/input/faceswap/source.jpg --target=example/input/faceswap/target.jpg
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "scripts/face_swap.py", line 26, in <module>
    from src.models.networks import Net3
  File "C:\Users\user\e4s\scripts\src\models\networks.py", line 8, in <module>
    from src.models.stylegan2.model import EqualLinear
  File "C:\Users\user\e4s\scripts\src\models\stylegan2\model.py", line 11, in <module>
    from src.models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "C:\Users\user\e4s\scripts\src\models\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\user\e4s\scripts\src\models\stylegan2\op\fused_act.py", line 9, in <module>
    fused = load(
  File "C:\Users\user\miniconda3\envs\e4s\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\user\miniconda3\envs\e4s\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\user\miniconda3\envs\e4s\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\user\miniconda3\envs\e4s\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\user\miniconda3\envs\e4s\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\user\miniconda3\envs\e4s\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\miniconda3\envs\e4s\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

(e4s) C:\Users\user\e4s>conda list
# packages in environment at C:\Users\user\miniconda3\envs\e4s:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2023.01.10           haa95532_0
certifi                   2023.5.7         py38haa95532_0
cffi                      1.15.1           py38h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1           py38h21b164f_0
cuda                      12.1.1                        0    nvidia
cuda-cccl                 12.1.109                      0    nvidia
cuda-command-line-tools   12.1.1                        0    nvidia
cuda-compiler             12.1.1                        0    nvidia
cuda-cudart               12.1.105                      0    nvidia
cuda-cudart-dev           12.1.105                      0    nvidia
cuda-cuobjdump            12.1.111                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-cuxxfilt             12.1.105                      0    nvidia
cuda-demo-suite           12.1.105                      0    nvidia
cuda-documentation        12.1.105                      0    nvidia
cuda-libraries            12.1.1                        0    nvidia
cuda-libraries-dev        12.1.1                        0    nvidia
cuda-nsight-compute       12.1.1                        0    nvidia
cuda-nvcc                 12.1.105                      0    nvidia
cuda-nvdisasm             12.1.105                      0    nvidia
cuda-nvml-dev             12.1.105                      0    nvidia
cuda-nvprof               12.1.105                      0    nvidia
cuda-nvprune              12.1.105                      0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvrtc-dev            12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-nvvp                 12.1.105                      0    nvidia
cuda-opencl               12.1.105                      0    nvidia
cuda-opencl-dev           12.1.105                      0    nvidia
cuda-profiler-api         12.1.105                      0    nvidia
cuda-runtime              12.1.1                        0    nvidia
cuda-sanitizer-api        12.1.105                      0    nvidia
cuda-toolkit              12.1.1                        0    nvidia
cuda-tools                12.1.1                        0    nvidia
cuda-visual-tools         12.1.1                        0    nvidia
cudatoolkit               11.3.1               h59b6b97_2
cycler                    0.11.0                   pypi_0    pypi
filelock                  3.9.0            py38haa95532_0
fonttools                 4.39.4                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
giflib                    5.2.1                h8cc25b3_3
idna                      3.4              py38haa95532_0
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319
jinja2                    3.1.2            py38haa95532_0
jpeg                      9e                   h2bbff1b_1
kiwisolver                1.4.4                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libcublas                 12.1.3.1                      0    nvidia
libcublas-dev             12.1.3.1                      0    nvidia
libcufft                  11.0.2.54                     0    nvidia
libcufft-dev              11.0.2.54                     0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurand-dev             10.3.2.106                    0    nvidia
libcusolver               11.4.5.107                    0    nvidia
libcusolver-dev           11.4.5.107                    0    nvidia
libcusparse               12.1.0.106                    0    nvidia
libcusparse-dev           12.1.0.106                    0    nvidia
libdeflate                1.17                 h2bbff1b_0
libffi                    3.4.4                hd77b12b_0
libnpp                    12.1.0.40                     0    nvidia
libnpp-dev                12.1.0.40                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjitlink-dev          12.1.105                      0    nvidia
libnvjpeg                 12.2.0.2                      0    nvidia
libnvjpeg-dev             12.2.0.2                      0    nvidia
libnvvm-samples           12.1.105                      0    nvidia
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.0                h6c2663c_2
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
lz4-c                     1.9.4                h2bbff1b_0
markupsafe                2.1.1            py38h2bbff1b_0
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2023.1.0         h8bd8f75_46356
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.6            py38hf11a4ad_1
mkl_random                1.2.2            py38hf11a4ad_1
mpmath                    1.2.1            py38haa95532_0
networkx                  2.8.4            py38haa95532_1
ninja                     1.11.1                   pypi_0    pypi
nsight-compute            2023.1.1.4                    0    nvidia
numpy                     1.24.3           py38h79a8e48_1
numpy-base                1.24.3           py38h8a87ada_1
openssl                   1.1.1t               h2bbff1b_0
pillow                    9.4.0            py38hd77b12b_0
pip                       23.0.1           py38haa95532_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 23.0.0           py38haa95532_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
python                    3.8.16               h6244533_3
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
pyyaml                    6.0                      pypi_0    pypi
requests                  2.29.0           py38haa95532_0
setuptools                66.0.0           py38haa95532_0
sqlite                    3.41.2               h2bbff1b_0
sympy                     1.11.1           py38haa95532_0
tbb                       2021.8.0             h59b6b97_0
tk                        8.6.12               h2bbff1b_0
torch                     2.0.1+cu118              pypi_0    pypi
torchvision               0.15.2                 py38_cpu    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.5.0            py38haa95532_0
urllib3                   1.26.15          py38haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
xz                        5.4.2                h8cc25b3_0
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

**Comment by e4s2022** [comment]
Windows env is not recommended.

**Comment by unknownperson3000** [comment]
???
imbossible to fix?
